language: node_js
node_js:
  - "0.8"

before_install:
  - "curl http://apt.basho.com/gpg/basho.apt.key | sudo apt-key add -"
  - 'sudo bash -c "echo deb http://apt.basho.com $(lsb_release -sc) main > /etc/apt/sources.list.d/basho.list"'
  - "sudo apt-get update"
  - "yes n | sudo apt-get install riak --force-yes"
  - "sudo service riak start"

before_script: sudo /usr/sbin/search-cmd install test
